<h1>Form insert that data in database</h1>

<form action="<?php echo $block->getFormAction() ?>" method="post">
    <input name="sku" type="text" placeholder="Nhập sku">
    <input name="name" type="text" placeholder="Nhập name">
    <input name="price" type="text" placeholder="Nhập price">
    <input name="quantity" type="text" placeholder="Nhập quantity">
    <input type="submit" value="Send product informations">
</form>